export type TokenType =
    | "Text"
    | "Dollar"
    | "DoubleDollar"
    | "LeftParenthesis"
    | "RightParenthesis"
    | "LeftSquareBracket"
    | "RightSquareBracket"
    | "Dot"
    | "Colon"
    | "SemiColon"
    | "Comma"
    | "Space"
    | "DoubleQuotation"
    | "String"
    | "Equal"
    | "Plus"
    | "Minus"
    | "Slash"
    | "Asterisk"
    | "Percent"
    | "Bang"
    | "Ampersand"
    | "VerticalLine"
    | "LessThan" /* < */
    | "GreaterThan" /* > */;
